version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    #restart: always
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      # Add other environment variables for your Node.js app
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    #restart: always
    ports:
      - "82:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    container_name: db
    image: mysql:8.0
    ports:
      - "33006:3306"
    #restart: always
    environment:
      # Set MySQL root password and other configurations
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge